import { useState } from 'react';
import { Link } from 'react-router-dom';
import { auth } from '../../firebaseConfig'; // Importamos la configuración de Firebase
import { createUserWithEmailAndPassword } from 'firebase/auth'; // Importamos la función de registro
import './Register.css';

const Register = () => {
  // 1. Creamos "memorias" (estados) para guardar lo que el usuario escribe
    const [email, setEmail] = useState('');
      const [password, setPassword] = useState('');
        const [name, setName] = useState('');
          const [error, setError] = useState(''); // Un estado para mensajes de error

            // 2. Esta es la función que se ejecuta al enviar el formulario
              const handleRegister = async (e: React.FormEvent) => {
                  e.preventDefault(); // Previene que la página se recargue
                      setError(''); // Limpiamos errores previos

                          try {
                                // 3. Llamamos a la función mágica de Firebase para crear el usuario
                                      const userCredential = await createUserWithEmailAndPassword(auth, email, password);
                                            console.log('Usuario creado:', userCredential.user);
                                                  alert('¡Cuenta creada con éxito!'); // Mostramos un mensaje de éxito

                                                        // Aquí en el futuro, podríamos añadir el nombre a la base de datos de Firestore
                                                              // y redirigir al usuario al juego.

                                                                  } catch (err: any) {
                                                                        // 4. Si Firebase devuelve un error, lo atrapamos y lo mostramos
                                                                              console.error("Error al registrar:", err.message);
                                                                                    setError(err.message); // Guardamos el mensaje de error para mostrarlo
                                                                                          alert(`Error: ${err.message}`); // Y también lo mostramos en una alerta
                                                                                              }
                                                                                                };

                                                                                                  return (
                                                                                                      <div className="auth-container">
                                                                                                            <video autoPlay loop muted className="auth-video-bg">
                                                                                                                    <source src="/videos/fondo-casino.mp4" type="video/mp4" />
                                                                                                                          </video>

                                                                                                                                <div className="auth-form-box">
                                                                                                                                        <h2 className="auth-title">Crear Cuenta</h2>
                                                                                                                                                <p className="auth-subtitle">Únete a la experiencia Bingo Royale</p>
                                                                                                                                                        {/* 5. Conectamos nuestra función al evento 'onSubmit' del formulario */}
                                                                                                                                                                <form onSubmit={handleRegister}>
                                                                                                                                                                          <div className="input-group">
                                                                                                                                                                                      <label htmlFor="name">Nombre Completo</label>
                                                                                                                                                                                                  {/* Conectamos los inputs a su "memoria" */}
                                                                                                                                                                                                              <input 
                                                                                                                                                                                                                            type="text" 
                                                                                                                                                                                                                                          id="name" 
                                                                                                                                                                                                                                                        value={name} 
                                                                                                                                                                                                                                                                      onChange={(e) => setName(e.target.value)} 
                                                                                                                                                                                                                                                                                    required 
                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                    <div className="input-group">
                                                                                                                                                                                                                                                                                                                                <label htmlFor="email">Correo Electrónico</label>
                                                                                                                                                                                                                                                                                                                                            <input 
                                                                                                                                                                                                                                                                                                                                                          type="email" 
                                                                                                                                                                                                                                                                                                                                                                        id="email" 
                                                                                                                                                                                                                                                                                                                                                                                      value={email} 
                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setEmail(e.target.value)} 
                                                                                                                                                                                                                                                                                                                                                                                                                  required 
                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="input-group">
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <label htmlFor="password">Contraseña</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <input 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        type="password" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      id="password" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={password} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={(e) => setPassword(e.target.value)} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                required 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button type="submit" className="auth-button">Registrarse</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="auth-disclaimer">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p>Debes ser mayor de 18 años para jugar.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p>Se permite una sola cuenta por persona.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="auth-link">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>¿Ya tienes una cuenta? <Link to="/login">Inicia Sesión</Link></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export default Register;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  